### ISSUE TITLE
bug: tabBar icon add fail

### ISSUE THREAD

**Issue by su9er** [realywithoutname/mini-program-webpack-loader#17]
https://github.com/realywithoutname/mini-program-webpack-loader/blob/a46e4cc1bf16eb9a6498eb8891d012afbf7a4265/src/MiniProgram.js#L253

should be:
`
    entrys = entrys.concat((tabBar && tabBar.list && getTabBarIcons(this.mainContext, tabBar.list)) || [])
`

**Comment by realywithoutname** [comment]
fixed in mini-program-webpack-loader@0.2.11
