### ISSUE TITLE
您使用的是什么编辑器？

### ISSUE THREAD

**Issue by hanwenbo** [realywithoutname/mini-program-webpack-loader#19]
webstorm可以通过定义wenpack文件来索引到某个目录，ctrl+鼠标左键即可进入
但是json文件是索引不过去的，请问您是如何索引的呢
这个不算问题哦，是个帮助
{
  "usingComponents": {
    "rate": "@/components/rate/index"
  }
}

**Comment by realywithoutname** [comment]
vscode 一般这种都是使用 command + p 搜索
