### ISSUE TITLE
这种需要用什么loader呢

### ISSUE THREAD

**Issue by hanwenbo** [realywithoutname/mini-program-webpack-loader#20]
```js
export default class Exception {
    message;
    code;

    constructor(message, code) {
        console.log(message,code)
        this.message = message
        this.code = code
    }

    getCode() {
        return this.code
    }

    getMessage() {
        return this.message
    }
}



```
提示：
Module parse failed: Unexpected token (2:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Exception {

这种需要用什么loader呢，抱歉啊 对webpack的loader不太了解

**Comment by realywithoutname** [comment]
babel 版本问题
