### ISSUE TITLE
入口文件允许打包对应的 scss或less 文件

### ISSUE THREAD

**Issue by julytian** [realywithoutname/mini-program-webpack-loader#22]
https://github.com/realywithoutname/mini-program-webpack-loader/blob/a46e4cc1bf16eb9a6498eb8891d012afbf7a4265/src/MiniProgram.js#L226

这里希望`app.wxss`可以允许可以修改为`app.scss`或`app.less`。如下:
```js
let entryFiles = getFiles(itemContext, fileName, ['.wxss','.scss','.less'])
```

**Comment by realywithoutname** [comment]
mini-program-webpack-loader@0.2.12
