### ISSUE TITLE
请问这个支持ts吗

### ISSUE THREAD

**Issue by 2016geek** [realywithoutname/mini-program-webpack-loader#23]
这边能增加ts的配置吗

**Comment by realywithoutname** [comment]
mini-program-webpack-loader@0.2.13-beta.1

简单测试了可以支持，如果遇到问题欢迎基于 feature/ts 提 pr

**Comment by loveholly** [comment]
@realywithoutname webpack这边的配置需要怎么改吗？好像我使用`ts-loader`之后，ts文件并没有被编译

**Comment by realywithoutname** [comment]
不需要修改吧，我记得测试的时候，我就没有用 ts-loader，ts也是正常编译的，你可以试试，或者提供个demo，我有时间试试

**Comment by realywithoutname** [comment]
@loveholly 你看下需要的版本，有问题提供下 demo 或者自己解决

**Comment by loveholly** [comment]
我就是用首页提供的[小程序插件项目和普通小程序项目打包示例](https://github.com/realywithoutname/mini-loader-plugin-demo)，只是把`index.js`修改成了`index.ts`, `app.js`修改成`app.ts`，并且把依赖的插件版本改成了`0.2.12`

**Comment by realywithoutname** [comment]
mini-program-webpack-loader@0.2.13-beta.1 
这个版本，看上面的信息

**Comment by loveholly** [comment]
还是我搞错了版本😭

**Comment by jypblue** [comment]
@realywithoutname 最新的1.2.3版本支持ts的编译么？还是需要自己添加ts-loader?
