### ISSUE TITLE
build模式下报错，dev下没问题

### ISSUE THREAD

**Issue by hanwenbo** [realywithoutname/mini-program-webpack-loader#24]
![image](https://user-images.githubusercontent.com/5869741/62437182-c3c3f700-b774-11e9-8037-0e18c3a796c1.png)
我看代码只有--mode 不同

**Comment by hanwenbo** [comment]
不行 测试了 build下 不支持redux

**Comment by realywithoutname** [comment]
提供个 demo

**Comment by hanwenbo** [comment]
好了，感谢库主  webpack 增加 concatenateModules:false即可
