### ISSUE TITLE
使用0.2.12的版本，在构建ts的时候依然会出现错误信息

### ISSUE THREAD

**Issue by loveholly** [realywithoutname/mini-program-webpack-loader#28]
webpack loader的配置如下：

```js
{
    test: /\.ts$/,
    include: path.resolve(__dirname, '../plugin'),
    exclude: path.resolve(__dirname, '../node_modules'),
    use: [
      'cache-loader',
      'babel-loader',
      'ts-loader',
    ],
  },
```

在编译的时候提示：

**src/miniprogram/app.js 不应该不存在**

这个报错就很奇怪了，我把我的源码都改成了TS文件为啥校验的时候还去看JS后缀？

https://github.com/realywithoutname/mini-program-webpack-loader/blob/c82136d2cb32f205ffce4cf9c8e87292d9045741/src/MiniPlugin.js#L195

**Comment by loveholly** [comment]
我就是用首页提供的[小程序插件项目和普通小程序项目打包示例](https://github.com/realywithoutname/mini-loader-plugin-demo)，只是把`index.js`修改成了`index.ts`, `app.js`修改成`app.ts`，并且把依赖的插件版本改成了`0.2.12`

**Comment by realywithoutname** [comment]
另外个 [issue#23](https://github.com/realywithoutname/mini-program-webpack-loader/issues/23) 处理吧
