### ISSUE TITLE
对于通过npm安装的component有什么好的解决方案吗？

### ISSUE THREAD

**Issue by loveholly** [realywithoutname/mini-program-webpack-loader#29]
举例来说，我使用的`weui-miniprogram`就是通过npm安装的，我也希望这种第三方组件是通过npm管理，方便管理和维护，目前我的做法是在webpack这边配置`alias`：

```js
weui: resolve('node_modules/weui-miniprogram/miniprogram_dist')
```

以上做法虽然也能正常将组件编译过去，但是会提示一些错误信息：

`xxx路径错误：不应该还包含 node_modules`

似乎源码里面还会因为这个原因最终导致部分资源不会编译完成？请问有什么好的解决方案吗？

**Comment by realywithoutname** [comment]
你直接使用这个 npm 包名就可以了呀，不需要设置 alias，自动会找node_modules。小程序的所有文件类型都支持使用 alias 别名和 node_modules 包名

**Comment by jypblue** [comment]
@realywithoutname 可以给一下引入事例么？ 类似于``` "van-button": "/node_modules/@vant/weapp/dist/button/index"``` 这样？

**Comment by realywithoutname** [comment]
```json
"usingComponents": {
  "van-button": "@vant/weapp/dist/button/index"
}
```

就可以了，如果需要alias，可以 webpack resolve.alias 配置
```
{
  '@vant': "@vant/weapp/dist"
}
```
这样就可以：

```json
"usingComponents": {
  "van-button": "@vant/button/index"
}
```

**Comment by jypblue** [comment]
@realywithoutname thx

**Comment by jypblue** [comment]
![image](https://user-images.githubusercontent.com/5317786/104472179-a85e4c00-55f6-11eb-9a98-69210ca2e802.png)
![image](https://user-images.githubusercontent.com/5317786/104472376-dc397180-55f6-11eb-83af-afe55aca6873.png)

**Comment by jypblue** [comment]
引入@vant后wxml中的相对路径无法识别引入对应的文件
