### ISSUE TITLE
请问为什么在生成模式打包后app.js的大小是0，文件内什么都没有，但是开发模式打包时正常的？

### ISSUE THREAD

**Issue by sjava** [realywithoutname/mini-program-webpack-loader#32]

**Comment by sjava** [comment]
Time: 1308ms                                                                                                                                                          [15/331]
Built at: 2020/01/03 下午10:21:34                                                                                                                                             
                          Asset       Size  Chunks             Chunk Names                                                                                                    
                         app.js    0 bytes       4  [emitted]  app                                                                                                            
                       app.json  452 bytes          [emitted]                                                                                                                 
                       app.wxss  185 bytes          [emitted]                                                                                                                 
                     commons.js   19.3 KiB       0  [emitted]  commons                                                                                                        
  components/pages/logs/logs.js  301 bytes       5  [emitted]  components/pages/logs/logs                                                                                     
components/pages/logs/logs.json   77 bytes          [emitted]                                                                                                                 
components/pages/logs/logs.wxml  173 bytes          [emitted]                                                                                                                 
components/pages/logs/logs.wxss   83 bytes          [emitted]                                                                                                                 
           pages/index/index.js   1.02 KiB       7  [emitted]  pages/index/index                                                                                              
         pages/index/index.json   27 bytes          [emitted]                                                                                                                 
         pages/index/index.wxml  512 bytes          [emitted]                                                                                                                 
         pages/index/index.wxss  198 bytes          [emitted]                                                                                                                 
             pages/logs/logs.js  295 bytes       8  [emitted]  pages/logs/logs                                                                                                
           pages/logs/logs.json   77 bytes          [emitted]  
           pages/logs/logs.wxml  173 bytes          [emitted]  
           pages/logs/logs.wxss   83 bytes          [emitted]  
             webpack-require.js   2.73 KiB          [emitted]  
Entrypoint main = commons.js main.js
Entrypoint __assets_chunk_name__0 = commons.js __assets_chunk_name__0.js
Entrypoint components/pages/logs/logs = commons.js components/pages/logs/logs.js
Entrypoint pages/index/index = commons.js pages/index/index.js
Entrypoint pages/logs/logs = commons.js pages/logs/logs.js
Entrypoint __assets_chunk_name__1 = commons.js __assets_chunk_name__1.js
Entrypoint app = commons.js app.js
Entrypoint __assets_chunk_name__2 = commons.js __assets_chunk_name__2.js
[11] ./utils/rxjs/index.js + 7 modules 9.79 KiB {0} [built]
     | ./utils/rxjs/index.js 1.33 KiB [built]
     | ./utils/promisify.js 225 bytes [built]
     |     + 6 hidden modules
[18] ./utils/util.js 566 bytes {0} [built]
[21] ./app.json 54 bytes {0} [built]
[24] multi ./components/pages/logs/logs.json ./components/pages/logs/logs.wxml ./components/pages/logs/logs.scss ./pages/index/index.json ./pages/index/index.wxml ./pages/index/index.scss ./pages/logs/logs.json ./pages/logs/logs.wxml ./pages/logs/logs.scss ./app.scss ./app.json 148 bytes {1} [built]
[28] ./pages/index/index.json 68 bytes {1} [built]
[29] ./pages/index/index.wxml 68 bytes {1} [built]
[30] ./pages/index/index.scss 68 bytes {1} [built]
[31] ./pages/logs/logs.json 66 bytes {1} [built]
[32] ./pages/logs/logs.wxml 66 bytes {1} [built]
[33] ./pages/logs/logs.scss 66 bytes {1} [built]
[34] ./app.scss 54 bytes {1} [built]
[36] ./pages/index/index.js 1.77 KiB {7} [built]
[37] ./pages/logs/logs.js 261 bytes {8} [built]
[38] ./app.js + 1 modules 1.73 KiB {4} [built]
     | ./app.js 1.63 KiB [built]
     | ./utils/demo.js 84 bytes [built]
[40] multi  16 bytes {0} [built]
    + 180 hidden modules

time          status   watch  page  component  subpackage  duration  size     hash                 
------------  -------  -----  ----  ---------  ----------  --------  -------  --------------------
下午10:21:34  success  21/17  3     0          1/1         1.308s    25.66 k  b412cb287a4def20a85d

Done in 1.99s.

**Comment by realywithoutname** [comment]
应该是配置问题，可以参考demo

**Comment by realywithoutname** [comment]
https://github.com/realywithoutname/mini-loader-plugin-demo/issues/3

**Comment by sjava** [comment]
增加 concatenateModules:false,app.js就不为空了。不知道为什么不能开启concatenateModules，生产模式一般都是开启的。
// test.js
export const a = 1
// app.js
import { a } from './test.js'
当test.js只在app.js中引入,没有其他js引入test.js时,开启concatenateModules后,打包出来的app.js就为空,供参考.
