### ISSUE TITLE
windows下能使用吗 ？

### ISSUE THREAD

**Issue by jetBn** [realywithoutname/mini-program-webpack-loader#41]

**Comment by jetBn** [comment]
通过yarn安装的依赖报错

**Comment by jetBn** [comment]
版本0.2.10以下会报错  
![image](https://user-images.githubusercontent.com/26957220/82400839-dcdf2f80-9a8a-11ea-8e8c-4adba5240dcc.png)

**Comment by jetBn** [comment]
安装0.2.10正常 我以为是安装依赖使用的yarn还是npm的问题  ，然后通过两种方式安装都一样。

**Comment by jetBn** [comment]
然后安装你们现在发布的1.0.13最新版本也是有问题的，运行报错。

**Comment by realywithoutname** [comment]
我看报错的包 https://github.com/qq157788394/mini-program-webpack-loader-boilerplate 这个，你可以试着解决下

**Comment by jetBn** [comment]
我安装0.2.10又正常了

**Comment by jetBn** [comment]
> 我看报错的包 https://github.com/qq157788394/mini-program-webpack-loader-boilerplate 这个，你可以试着解决下

他这个也会吧 我试了好像
