### ISSUE TITLE
1.x是不是用不了

### ISSUE THREAD

**Issue by whereiscode** [realywithoutname/mini-program-webpack-loader#46]
我是从0.2开始用的一直没升级过

我刚才遇到问题尝试升级到1.x，但发现内存溢出

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by whereiscode** [comment]
1.x好像要监听特别多的文件，因为从监听到报错间隔了5分钟朝上

webpack is watching the files…
...............
然后>5分钟后报错
....
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by whereiscode** [comment]
修改helpers里的compoent.js的
```js
 /**
   * 自定义组件
   */
  let normalPromises = forEachUsingComponent(usingComponents, async (key, item) => {
    if (/^plugin:\/\//.test(item) || /^plugin-private:\/\//.test(item) ) {
      return tree.addComponent(request, key, '', [])
    }
    let componentPath = await handelComponent(key, item)
    normalCallBack && normalCallBack(componentPath, key, usingComponents)
  })
```

这样可以不编译，但是我不知道怎么通过配置解决这个问题

**Comment by realywithoutname** [comment]
mini-program-webpack-loader@1.0.15
