### ISSUE TITLE
webpack 配置不对哦，该插件只支持 wxml, wxss, wxs, json 

### ISSUE THREAD

**Issue by jensenfan** [realywithoutname/mini-program-webpack-loader#47]
HI
大佬
这个插件我在使用过程中遇到点问题，按照文档推荐配置完成之后，运行  报了标题上的错误。
在0.2.8版本上没有这个问题，最新版本一直都有这个问题
请问什么时候能修复一下呢？或者说目前有没有什么好的解决方法
![image](https://user-images.githubusercontent.com/24409393/85494586-8de96480-b60b-11ea-993f-3b1f5fc12fc3.png)

**Comment by realywithoutname** [comment]
是不是存在隐藏文件，用 copy 插件导致参与到了打包呢

**Comment by jypblue** [comment]
我这边也出现这种情况了，版本是最新1.2.3

**Comment by jypblue** [comment]
![image](https://user-images.githubusercontent.com/5317786/104535877-f18fb980-5651-11eb-82e4-5f1474607b91.png)

如果用.scss就要报这个错误么？

**Comment by jypblue** [comment]
![image](https://user-images.githubusercontent.com/5317786/104539097-e3dd3280-5657-11eb-9cee-e8111378dd81.png)
@realywithoutname 这样控制台就不报错了
