### ISSUE TITLE
请问可以支持一下抖音小程序的文件类型么？

### ISSUE THREAD

**Issue by jypblue** [realywithoutname/mini-program-webpack-loader#50]
想着用这个loader，配置抖音小程序开发脚手架，看了源码只支持支付宝和微信的文件后缀类型，希望支持一下抖音的后缀类型

**Comment by realywithoutname** [comment]
我自己目前没有这样的需求，可能并不能很好的支持，所以没有计划。不过你可以 fork 根据自己的需求开发。

**Comment by jypblue** [comment]
thx
