### ISSUE TITLE
在app.json中的usingComponents字段会在打包之后消失，导致全局组件无法加载，路径别名已配置正确，页面的index.json中配置usingComponents正常

### ISSUE THREAD

**Issue by MatrixAge** [realywithoutname/mini-program-webpack-loader#51]
手动通过entry.eccept.usingComponents字段设定打包之后app.json中也没有usingComponents，求解。

**Comment by MatrixAge** [comment]
helpers文件夹下面的`parse-entry.js`中导出了一个`getEntryConfig(pluginEntryConfig, appJsonConfig)=>config`方法，但是并没有使用，其中处理usingComponents字段的逻辑也没用上，所以是不是遗漏了呢？

**Comment by realywithoutname** [comment]
app.json 的 usingComponents 会在编译时处理到使用的组件或者页面中，app.json 中就不会有 usingComponents 了。

**Comment by MatrixAge** [comment]
使用你仓库中的那个demo，然后添加在app.json中添加components之后，然后在页面使用，编译通过，但并没有打包的页面中。我粗暴地直接把copy app.json => dist/app.json，暂时解决了问题，但这种方式可能有隐患，不符合使用webpack的规范。

找了一遍使用过该插件的那些仓库的配置，全都没有在app.json中使用usingComponents配置过全局自定义组件，所以你可以更新一下demo，让后面的人也好发现是哪儿出了问题。

```js
compilationFinish(){
        fs.copyFile(paths.app_json, paths.dist_app_json, (err) => {
		if (err) console.log(err)
	})
}
```

**Comment by realywithoutname** [comment]
我们在业务中也是使用的全局usingComponents，业务都是正常的呢。用到的组件都会自动打包到对应的分包或者主包的。你可以再看下，如果还有问题可以建个复现 Demo。微信原生的usingComponents以前是会往每个json文件拷贝全局组件，导致包体积变大的，所以我们才会把他编译到各个用到的包中。

**Comment by MatrixAge** [comment]
[https://github.com/MatrixAges/light-design](https://github.com/MatrixAges/light-design)
components是组件目录，alias也配置了，打包之后，app.json没有usingComponents字段

**Comment by MatrixAge** [comment]
组件库第一版完成之后，会抽时间自己写几个loader和plugin来实现我的特定需求，到时候会参考您的loader，目前已经可以用起来了，感谢帮助啦，close了.

**Comment by realywithoutname** [comment]
![image](https://user-images.githubusercontent.com/10306332/99138437-6c951d80-266b-11eb-98f2-c1f3db446344.png)
在 xml 中，组件都是小写字母，不能用大写。会被转为小写，然后和 app.json 里面的匹配不上，所以会没有。
![image](https://user-images.githubusercontent.com/10306332/99138475-bd0c7b00-266b-11eb-9aef-92d375aa68d7.png)
改为小写后，app 的 usingcomponents 会自动添加到组件内的。

**Comment by MatrixAge** [comment]
soga，用React风格的写法写web-components果然有问题，记住了，3ks。
