### ISSUE TITLE
app.json里面的subPackages写法

### ISSUE THREAD

**Issue by julytian** [realywithoutname/mini-program-webpack-loader#52]
[app.json官方文档配置](https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages/basic.html)现在的分包字段使用了` subpackages` 字段，虽然写成 `subPackages ` 也支持。但作者这里只支持 subPackages写法。如果按照文档的写法写成 subpackages 打包出来是没有效果的。

**Comment by realywithoutname** [comment]
暂时不会修改了，先用着把
