### ISSUE TITLE
TypeError: DomHandler is not a constructor

### ISSUE THREAD

**Issue by feng138168** [realywithoutname/mini-program-webpack-loader#56]
mini-loader-plugin-demo跑起来无法正常编译wxml，发现是html-mini-loader.js的domhandler有问题
`const DomHandler = require('domhandler').default`
加上.default就可以了

**Comment by realywithoutname** [comment]
里面用的 htmlparser2 ^3.9.2, domhandler 版本可以降到 2.x，高版本的 domhandler 不兼容

**Comment by WangZhenHao** [comment]
npm install 安装有问题，使用yarn install 就好了
